### ISSUE TITLE
[Occasional panic]: runtime error: slice bounds out of range [:2048] with capacity 47

### ISSUE THREAD

**Issue by flyaways** [tsuna/gohbase#144]
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/sirupsen/logrus"
	"github.com/tsuna/gohbase"
	"github.com/tsuna/gohbase/filter"
	"github.com/tsuna/gohbase/hrpc"
)

func init() {
	logrus.SetOutput(os.Stdout)
	logrus.SetLevel(logrus.ErrorLevel)
}

var (
	zk       = flag.String("zk", "*****", "zkquorum")
	table    = flag.String("t", "livexxxx", "table")
	key      = flag.String("k", "1xxxxxxxxxxxxxxxxxxxx", "-key")
	nClients = flag.Int("nClients", 1, "-nClients")
	rows     = flag.Int("rows", 1, "-rows")
	value    = map[string]map[string][]byte{"cf": {"a": {0}}}
	f        = map[string][]string{"cf": {"a"}}
)

func main() {
	flag.Parse()

	Admin()
	now := time.Now()
	{
		var g sync.WaitGroup
		g.Add(*nClients)
		for i := 0; i < *nClients; i++ {
			go Increment(i, &g)
		}
		g.Wait()
	}
	cost := time.Since(now)
	fmt.Println("Incr:	", *nClients**rows, cost.String(), 1000**nClients**rows/int(cost.Milliseconds()))

	now = time.Now()
	{
		var g sync.WaitGroup
		g.Add(*nClients)
		for i := 0; i < *nClients; i++ {
			go Put(i, &g)
		}
		g.Wait()
	}
	cost = time.Since(now)
	fmt.Println("Put:	", *nClients**rows, cost.String(), 1000**nClients**rows/int(cost.Milliseconds()))

	now = time.Now()
	{
		var g sync.WaitGroup
		g.Add(*nClients)
		for i := 0; i < *nClients; i++ {
			go Get(i, &g)
		}
		g.Wait()
	}
	cost = time.Since(now)
	fmt.Println("Get:	", *nClients**rows, cost.String(), 1000**nClients**rows/int(cost.Milliseconds()))
}

func Admin() {
	fmt.Println("NewAdminClient")
	admin := gohbase.NewAdminClient(*zk)
	// status, _ := admin.ClusterStatus()

	fmt.Println("ListTableNames")
	t, _ := hrpc.NewListTableNames(context.Background())
	tablenames, _ := admin.ListTableNames(t)

	for _, t := range tablenames {
		admin.DisableTable(hrpc.NewDisableTable(context.Background(), t.GetQualifier()))
		admin.DeleteTable(hrpc.NewDeleteTable(context.Background(), t.GetQualifier()))
		log.Println(t.String())
	}

	fmt.Println("CreateTable", *table)
	_ = admin.CreateTable(hrpc.NewCreateTable(context.Background(), []byte(*table),
		map[string]map[string]string{"cf": nil, "cf2": nil}))

	fmt.Println("CreateTable", *table+"_incr")
	_ = admin.CreateTable(hrpc.NewCreateTable(context.Background(), []byte(*table+"_incr"),
		map[string]map[string]string{"cf": nil, "cf2": nil}))

}

func Increment(num int, g *sync.WaitGroup) {
	defer g.Done()
	client := gohbase.NewClient(*zk)
	defer client.Close()
	var b strings.Builder
	for i := 0; i < *rows; i++ {
		b.Reset()
		b.WriteString(*key)
		b.WriteString(strconv.Itoa(num))
		b.WriteString(strconv.Itoa(i))
		request, _ := hrpc.NewIncStrSingle(context.Background(), *table+"_incr", b.String(), "cf", "q", 1)
		if _, err := client.Increment(request); err != nil {
			log.Println(i, err)
		}
	}
}

func Put(num int, g *sync.WaitGroup) {
	defer g.Done()
	client := gohbase.NewClient(*zk)
	defer client.Close()
	var b strings.Builder
	for i := 0; i < *rows; i++ {
		b.Reset()
		b.WriteString(*key)
		b.WriteString(strconv.Itoa(num))
		b.WriteString(strconv.Itoa(i))
		request, _ := hrpc.NewPutStr(context.Background(), *table, b.String(),
			value)
		if _, err := client.Put(request); err != nil {
			log.Println(i, err)
		}
	}
}

func Get(num int, g *sync.WaitGroup) {
	defer g.Done()
	client := gohbase.NewClient(*zk)
	defer client.Close()
	var b strings.Builder
	for i := 0; i < *rows; i++ {
		b.Reset()
		b.WriteString(*key)
		b.WriteString(strconv.Itoa(num))
		b.WriteString(strconv.Itoa(i))
		request, _ := hrpc.NewGetStr(context.Background(), *table, b.String(),
			hrpc.Families(f), hrpc.Filters(filter.NewKeyOnlyFilter(true)))
		if _, err := client.Get(request); err != nil {
			log.Println(i, err)
		}
	}
}
```

```sh
go build && ./hbase -nClients 2000 -rows 300

NewAdminClient
ListTableNames
2020/08/13 20:27:41 namespace:"default"  qualifier:"livexxxx"
2020/08/13 20:27:43 namespace:"default"  qualifier:"livexxxx_incr"
CreateTable livexxxx
CreateTable livexxxx_incr
2020/08/13 20:27:48 18 increment returned 0 cells, but we expected exactly one
panic: runtime error: slice bounds out of range [:6449] with capacity 47

goroutine 20571 [running]:
github.com/tsuna/gohbase/hrpc.cellFromCellBlock(0xc000ac45b6, 0x3d, 0x3d, 0xc000fadf90, 0x819300, 0xc0000b4360, 0x38)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/hrpc/call.go:196 +0x747
github.com/tsuna/gohbase/hrpc.deserializeCellBlocks(0xc000ac45b6, 0x3d, 0x3d, 0x1, 0x7a7aa0, 0x7f1cfc57e0d8, 0xc01180ed48, 0x40f8f8, 0x40, 0x78dc80)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/hrpc/call.go:237 +0xd2
github.com/tsuna/gohbase/hrpc.(*Mutate).DeserializeCellBlocks(0xc0148cc6e0, 0x816b00, 0xc016b41080, 0xc000ac45b6, 0x3d, 0x3d, 0x0, 0xc0000f60e8, 0x81f880)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/hrpc/mutate.go:510 +0x9c
github.com/tsuna/gohbase/region.(*multi).DeserializeCellBlocks(0xc0148c3240, 0x816a80, 0xc002f84320, 0xc000ac45b6, 0x3d, 0x3d, 0x0, 0x0, 0x0)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/multi.go:188 +0x344
github.com/tsuna/gohbase/region.(*client).receive(0xc00d4864d0, 0x0, 0x0)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/client.go:545 +0x9f7
github.com/tsuna/gohbase/region.(*client).receiveRPCs(0xc00d4864d0)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/client.go:444 +0x6b
created by github.com/tsuna/gohbase/region.(*client).Dial.func1
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/new.go:71 +0x325
```

```sh
go build && ./hbase -nClients 2000 -rows 300

NewAdminClient
ListTableNames
2020/08/13 21:15:17 namespace:"default"  qualifier:"livexxxx"
2020/08/13 21:15:19 namespace:"default"  qualifier:"livexxxx_incr"
CreateTable livexxxx
CreateTable livexxxx_incr
panic: runtime error: slice bounds out of range [:2048] with capacity 47

goroutine 37751 [running]:
github.com/tsuna/gohbase/hrpc.cellFromCellBlock(0xc001fbeb56, 0x3d, 0x3d, 0xc002390558, 0x819300, 0xc000114360, 0x38)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/hrpc/call.go:196 +0x747
github.com/tsuna/gohbase/hrpc.deserializeCellBlocks(0xc001fbeb56, 0x3d, 0x3d, 0x1, 0x7a7aa0, 0x7fb73c56b1c0, 0xc0031d6d48, 0x40f8f8, 0x40, 0x78dc80)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/hrpc/call.go:237 +0xd2
github.com/tsuna/gohbase/hrpc.(*Mutate).DeserializeCellBlocks(0xc003264210, 0x816b00, 0xc00363be00, 0xc001fbeb56, 0x3d, 0x3d, 0x0, 0xc0001560e8, 0x81f880)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/hrpc/mutate.go:510 +0x9c
github.com/tsuna/gohbase/region.(*multi).DeserializeCellBlocks(0xc0049648c0, 0x816a80, 0xc002cb2be0, 0xc001fbeb56, 0x3d, 0x3d, 0x0, 0xc022168e50, 0x1)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/multi.go:188 +0x344
github.com/tsuna/gohbase/region.(*client).receive(0xc01c0c68f0, 0x0, 0x0)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/client.go:545 +0x9f7
github.com/tsuna/gohbase/region.(*client).receiveRPCs(0xc01c0c68f0)
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/client.go:444 +0x6b
created by github.com/tsuna/gohbase/region.(*client).Dial.func1
	/home/zhangdongdong2/go/pkg/mod/github.com/tsuna/gohbase@v0.0.0-20200713183215-6acaa09d18ed/region/new.go:71 +0x325

```
```sh
go build && ./hbase -nClients 2000 -rows 300

NewAdminClient
ListTableNames
2020/08/13 21:13:29 namespace:"default"  qualifier:"livexxxx"
2020/08/13 21:13:30 namespace:"default"  qualifier:"livexxxx_incr"
CreateTable livexxxx
CreateTable livexxxx_incr
Incr:	 600000 15.761756677s 38068
Put:	 600000 16.231813331s 36966
Get:	 600000 9.685018257s 61951
```

**Comment by timoha** [comment]
hey, thanks for reporting, that does sounds like a problem. I tried reproducing with your code on hbase 2.2.5, but wasn't able to hit this issue. Which version of HBase are you running also how many regionservers and regions do you have?

**Comment by timoha** [comment]
Also, in your 2 outputs the panic seems to happen when it's doing `Increment()`. That's interesting, could you try each of `Get`, `Put`, and `Increment` individually to narrow down if that's an issue only with increments.

**Comment by flyaways** [comment]
thanks for your reply,  OP locate this issue  was caused by  the server ， that the metadata was  broken(can't read or write)

basic info:
hbase version：  2.2.3
regionservers：  3 nodes(8 core & 32G SSD 800G)
master servers：2 nodes(4 core & 16G SSD 500G)
in this issue regions=1
