### ISSUE TITLE
tsuna / gohbase with Hbase server in standalone mode

### ISSUE THREAD

**Issue by fsunaval** [tsuna/gohbase#46]
This is most probably not an issue with tsuna / gohbase.  Hopefully, one of you can help me with a definitive answer.  The following is my code snippet.  Hbase is in "standalone mode".

package main
import (
        "context"
        "github.com/tsuna/gohbase"
        "github.com/tsuna/gohbase/hrpc"
)
const metaTableName = "hbase:meta"
var infoFamily = map[string][]string{
        "info": nil,
}
var cFamilies = map[string]map[string]string{
        "cf":  nil,
        "cf2": nil,
}
func main () {
        testTableName := "test1_"
        ac := gohbase.NewAdminClient("127.0.0.1")
        crt := hrpc.NewCreateTable(context.Background(), []byte(testTableName), cFamilies)
        if err := ac.CreateTable(crt); err != nil {
        }
}

When I run the client locally as the server (same server), things are fine. The table "test1_" is created.
root@project-computing-lab-farhad-2:~/hbase-1.2.5# bin/hbase shell
2017-05-11 17:46:40,273 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
HBase Shell; enter 'help<RETURN>' for list of supported commands.
Type "exit<RETURN>" to leave the HBase Shell
Version 1.2.5, rd7b05f79dee10e0ada614765bb354b93d615a157, Wed Mar  1 00:34:48 CST 2017

hbase(main):001:0> list
TABLE
test1_
1 row(s) in 0.2950 seconds

=> ["test1_"]
hbase(main):002:0> disable "test1_"
0 row(s) in 2.4520 seconds

hbase(main):003:0> drop "test1_"
0 row(s) in 1.2760 seconds

If I run the client from a remote machine, (code is exactly the same as above except the server IP address is now changed as follows).
       ac := gohbase.NewAdminClient("10.145.211.213")

I get a lot of these zookeeper failure messages
2017-05-11 17:59:15,628 INFO  [SyncThread:0] server.ZooKeeperServer: Established session 0x15bf8a69357000f with negotiated timeout 30000 for client /10.145.211.185:52456
2017-05-11 17:59:15,630 INFO  [ProcessThread(sid:0 cport:-1):] server.PrepRequestProcessor: Processed session termination for sessionid: 0x15bf8a69357000f
2017-05-11 17:59:15,631 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: Closed socket connection for client /10.145.211.185:52456 which had sessionid 0x15bf8a69357000f
2017-05-11 17:59:16,146 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxnFactory: Accepted socket connection from /10.145.211.185:52460
2017-05-11 17:59:16,146 INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.ZooKeeperServer: C

This is a very commonly reported issue on the web.  Some folks have suggested to reorder the listings in /etc/host as follows
http://stackoverflow.com/questions/7791788/hbase-client-do-not-able-to-connect-with-remote-hbase-server

I have tried all these suggestions but still keep getting the same error.   Can anyone give a definitive answer as to whether Hbase in standalone mode can support remote clients?

thanks,

**Comment by Timoha** [comment]
> Can anyone give a definitive answer as to whether Hbase in standalone mode can support remote clients?

HBase can definitely support remote clients regardless of the mode.

> If I run the client from a remote machine, (code is exactly the same as above except the server IP address is now changed as follows).

Could you modify your hbase-site.xml to point to the same IP address and try if hbase shell is working.

**Comment by fsunaval** [comment]
Thanks so much for responding.
Here's what I have.
client      hbase-server
client is running your go-hbase.
hbase-server is running Hbase in standalone mode.

Here is my original hbase-site.xml.  With this, the go-hbase client works fine when running on hbase-server but has issues when run remotely from the client.  If I don't have hbase.cluster.distributed set to true even though it is supposed to be in "standalone mode",  zookeeper gives other errors.
Original:   hbase-site.xml
<configuration>
  <property>
    <name>hbase.rootdir</name>
    <value>file:////root/db/hbase</value>
  </property>
  <property>
    <name>hbase.zookeeper.property.dataDir</name>
    <value>/root/db/zookeeper</value>
  </property>
  <property>
    <name>hbase.cluster.distributed</name>
    <value>true</value>
  </property>
</configuration>

After your suggestion, I modified hbase-site.xml as follows (not sure if I understood you correctly):

  <property>
    <name>hbase.rootdir</name>
    <value>file:////root/db/hbase</value>
  </property>
  <property>
    <name>hbase.zookeeper.property.dataDir</name>
    <value>/root/db/zookeeper</value>
  </property>
  <property>
    <name>hbase.cluster.distributed</name>
    <value>true</value>
  </property>
  <property>
    <name>hbase.zookeeper.quorum</name>
    <value>hbase-server</value>
  </property>

Atleast hbase server seems to start correctly.
root@hbase-server:~/hbase-1.2.5# bin/start-hbase.sh
localhost: starting zookeeper, logging to /root/hbase-1.2.5/bin/../logs/hbase-root-zookeeper-hbase-server.out
starting master, logging to /root/hbase-1.2.5/bin/../logs/hbase-root-master-project-hbase-server.out
starting regionserver, logging to /root/hbase-1.2.5/bin/../logs/hbase-root-1-regionserver-hbase-server.out

However, when I try to run hbase shell on hbase-server, it has issues.

root@hbase-server:~/hbase-1.2.5# bin/hbase shell
2017-05-11 20:42:28,055 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-05-11 20:42:45,302 ERROR [main] zookeeper.RecoverableZooKeeper: ZooKeeper exists failed after 4 attempts
2017-05-11 20:42:45,304 WARN  [main] zookeeper.ZKUtil: hconnection-0x2b10ace90x0, quorum=project-computing-lab-farhad-2:2181, baseZNode=/hbase Unable to set watcher on znode (/hbase/hbaseid)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:419)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:905)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:648)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:450)
        at org.jruby.javasupport.JavaMethod.invokeStaticDirect(JavaMethod.java:362)
        at org.jruby.java.invokers.StaticMethodInvoker.call(StaticMethodInvoker.java:58)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:312)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:169)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:169)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:191)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:144)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:148)
        at org.jruby.RubyClass.newInstance(RubyClass.java:822)
        at org.jruby.RubyClass$i$newInstance.call(RubyClass$i$newInstance.gen:65535)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:249)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:292)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
        at root.hbase_minus_1_dot_2_dot_5.bin.$_dot_dot_.bin.hirb.__file__(/root/hbase-1.2.5/bin/../bin/hirb.rb:131)
        at root.hbase_minus_1_dot_2_dot_5.bin.$_dot_dot_.bin.hirb.load(/root/hbase-1.2.5/bin/../bin/hirb.rb)
        at org.jruby.Ruby.runScript(Ruby.java:697)
        at org.jruby.Ruby.runScript(Ruby.java:690)
        at org.jruby.Ruby.runNormally(Ruby.java:597)
        at org.jruby.Ruby.runFromMain(Ruby.java:446)
        at org.jruby.Main.doRunFromMain(Main.java:369)
        at org.jruby.Main.internalRun(Main.java:258)
        at org.jruby.Main.run(Main.java:224)
        at org.jruby.Main.run(Main.java:208)
        at org.jruby.Main.main(Main.java:188)
2017-05-11 20:42:45,308 ERROR [main] zookeeper.ZooKeeperWatcher: hconnection-0x2b10ace90x0, quorum=project-computing-lab-farhad-2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid

Thanks so much for taking the time to respond to this thread. I do realize it probably has nothing to do with tsuna/gohbase issues.

In a way I am glad, I am not the only one having issues with this...
https://www.peopleperhour.com/job/i-need-an-hbase-standalone-setup-ready-to-use-for-remote-acc-338228

thanks,

**Comment by Timoha** [comment]
I'm going to close this issue as it looks like you are having the same problem with using the `hbase shell`, so it's not related to `gohbase`.

As for your problem, I'm a bit confused about why you have `hbase.cluster.distributed` set to `true`, but you say you want to start a standalone cluster.

Also, check if you have all the ports that hbase requires be allowed in your server's firewall. To me it looks like your issue doesn't have to do with hbase, but just with your infra setup (networking, firewall, etc). I can't really help more than that, you'd probably get more out of posting a question on Stackoverflow.
