### ISSUE TITLE
PatternFlags in Regex Scan function?

### ISSUE THREAD

**Issue by dockletinc** [tsuna/gohbase#56]
How I used Regex Scan filter?

**Comment by Timoha** [comment]
look into: https://godoc.org/github.com/tsuna/gohbase/filter#NewRegexStringComparator
you can cross reference how to use it by looking at hbase java doc: https://hbase.apache.org/devapidocs/org/apache/hadoop/hbase/filter/RegexStringComparator.html#RegexStringComparator-java.lang.String-int-org.apache.hadoop.hbase.filter.RegexStringComparator.EngineType-

**Comment by dockletinc** [comment]
Not clear in this point.
on "engine" and "charset" args

"**engine**" , "**charset**"  should set to something ref by java class?
`engine_scan = "org.apache.hadoop.hbase.filter.RegexStringComparator.EngineType.JAVA" // "JAVA"

  charset = "io.netty.util.CharsetUtil.ISO_8859_1" // ""ISO_8859_1" //  "ISO-8859-1"
`

i tried to set all of them but return errors

`resp.Next error : HBase Java exception org.apache.hadoop.hbase.DoNotRetryIOException: 
org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toFilter(ProtobufUtil.java:1537)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toScan(ProtobufUtil.java:1052)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.newRegionScanner(RSRpcServices.java:2475)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:2753)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:34950)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2339)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:123)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:188)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:168)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toFilter(ProtobufUtil.java:1533)
	... 8 more
Caused by: org.apache.hadoop.hbase.exceptions.DeserializationException: parseFrom called on base Filter, but should be called on derived type
	at org.apache.hadoop.hbase.filter.Filter.parseFrom(Filter.java:270)
	... 12 more
`

**## my simple scan with regex**
```
regex := fmt.Sprintf("^[0-9-a-f]{64}%s",suffix)
comp := filter.NewRegexStringComparator(regex, filter.CASE_INSENSITIVE, charset, engine_scan)
hl := filter.NewCompareFilter(filter.Equal, comp)
opts = append(opts, hrpc.Filters(hl))
sc , err := hrpc.NewScan(ctx,table,opts...)
res := client.Scan(scan)
...
```
What wrong? and how to fix it?
